# Generated by Django 5.2.7 on 2025-10-27 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Date')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='Sessions')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Visiteurs uniques')),
                ('total_pageviews', models.PositiveIntegerField(default=0, verbose_name='Pages vues')),
                ('avg_session_duration', models.FloatField(default=0, verbose_name='Durée moy (min)')),
                ('bounce_rate', models.FloatField(default=0, verbose_name='Taux rebond (%)')),
                ('conversion_rate', models.FloatField(default=0, verbose_name='Taux conversion (%)')),
                ('top_pages', models.JSONField(blank=True, null=True, verbose_name='Top pages')),
            ],
            options={
                'verbose_name': 'Analytique quotidienne',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(db_index=True, max_length=500, verbose_name='URL')),
                ('x_position', models.PositiveIntegerField(verbose_name='X')),
                ('y_position', models.PositiveIntegerField(verbose_name='Y')),
                ('click_count', models.PositiveIntegerField(default=1, verbose_name='Clics')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Heatmap',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Session')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Appareil')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navigateur')),
                ('screen_resolution', models.CharField(blank=True, max_length=50, verbose_name='Résolution')),
                ('referrer', models.TextField(blank=True, verbose_name='Référent')),
                ('landing_page', models.CharField(max_length=500, verbose_name='Landing Page')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='UTM Source')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='UTM Campaign')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Durée (sec)')),
                ('pages_visited', models.PositiveIntegerField(default=0, verbose_name='Pages visitées')),
                ('converted', models.BooleanField(default=False, verbose_name='Converti')),
            ],
            options={
                'verbose_name': 'Session',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500, verbose_name='URL')),
                ('page_title', models.CharField(blank=True, max_length=500, verbose_name='Titre')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Vu à')),
                ('time_on_page', models.PositiveIntegerField(default=0, verbose_name='Temps (sec)')),
                ('scroll_depth', models.PositiveIntegerField(default=0, verbose_name='Scroll (%)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'Vue de page',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Clic'), ('scroll', 'Scroll'), ('form_submit', 'Formulaire'), ('download', 'Téléchargement'), ('button', 'Bouton')], max_length=50, verbose_name='Type')),
                ('event_action', models.CharField(max_length=200, verbose_name='Action')),
                ('element_text', models.TextField(blank=True, verbose_name='Texte')),
                ('x_position', models.IntegerField(blank=True, null=True, verbose_name='X')),
                ('y_position', models.IntegerField(blank=True, null=True, verbose_name='Y')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['-timestamp'],
            },
        ),
    ]
