# Generated by Django 5.2.7 on 2025-10-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='show_statistics',
            field=models.BooleanField(default=True, help_text='Cochez pour afficher les statistiques (années, clients, projets)', verbose_name='Afficher les statistiques'),
        ),
    ]
