# Generated by Django 5.2.7 on 2025-10-29 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutsection_show_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('job_title', models.CharField(max_length=200, verbose_name='Titre/Poste')),
                ('tagline', models.CharField(help_text='Une phrase accrocheuse qui vous décrit', max_length=300, verbose_name='Tagline/Slogan')),
                ('bio', models.TextField(help_text='Description complète de votre profil et expertise', verbose_name='Biographie')),
                ('photo', models.ImageField(help_text='Photo professionnelle (format carré recommandé)', upload_to='business_card/', verbose_name='Photo de profil')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email professionnel')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Entrez un numéro de téléphone valide.')], verbose_name='Téléphone')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('company_logo', models.ImageField(blank=True, help_text='Logo de votre entreprise (format PNG transparent recommandé)', null=True, upload_to='business_card/logos/', verbose_name='Logo entreprise')),
                ('website_url', models.URLField(help_text='URL du site principal', validators=[django.core.validators.URLValidator()], verbose_name='Site web')),
                ('linkedin_url', models.URLField(help_text='URL complète de votre profil LinkedIn', validators=[django.core.validators.URLValidator()], verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Twitter/X')),
                ('github_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='GitHub')),
                ('accent_color', models.CharField(default='#3B82F6', help_text='Couleur hexadécimale (ex: #3B82F6)', max_length=7, verbose_name="Couleur d'accent")),
                ('background_gradient_start', models.CharField(default='#3B82F6', help_text='Couleur de début du fond dégradé', max_length=7, verbose_name='Couleur dégradé début')),
                ('background_gradient_end', models.CharField(default='#10B981', help_text='Couleur de fin du fond dégradé', max_length=7, verbose_name='Couleur dégradé fin')),
                ('is_active', models.BooleanField(default=True, help_text='Une seule carte peut être active à la fois', verbose_name='Actif')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, help_text='Nombre de fois que la carte a été consultée', verbose_name='Nombre de vues')),
                ('qr_scans_count', models.PositiveIntegerField(default=0, editable=False, help_text='Tracking approximatif des scans du QR code', verbose_name='Scans QR code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Carte de Visite Digitale',
                'verbose_name_plural': 'Cartes de Visite Digitales',
                'ordering': ['-created_at'],
            },
        ),
    ]
