# Generated by Django 5.2.7 on 2025-10-29 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_businesscard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Rejoignez notre équipe', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(default='Vous êtes un expert supply chain passionné ? Nous recherchons des talents pour renforcer notre équipe.', max_length=500, verbose_name='Description')),
                ('cta_text', models.CharField(default='Voir les opportunités', max_length=100, verbose_name='Texte du bouton CTA')),
                ('email', models.EmailField(default='recrutement@pinnacle-advisors.tech', help_text='Email vers lequel le bouton redirigera', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email de recrutement')),
                ('is_active', models.BooleanField(default=True, help_text='Décochez pour masquer la section recrutement sur le site', verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position dans la page (0 = en bas)', verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Section Recrutement',
                'verbose_name_plural': 'Section Recrutement',
                'ordering': ['order'],
            },
        ),
    ]
