# Generated by Django 5.2.7 on 2025-10-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_recruitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part1', models.CharField(default='Notre Équipe', help_text='Partie affichée avec gradient (ex: "Notre Équipe")', max_length=100, verbose_name='Première partie du titre')),
                ('title_part2', models.CharField(default="d'Experts", help_text='Partie affichée en noir (ex: "d\'Experts")', max_length=100, verbose_name='Seconde partie du titre')),
                ('description', models.TextField(default="Des professionnels passionnés avec plus de 15 ans d'expérience terrain en supply chain", max_length=300, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text="Décochez pour masquer l'en-tête personnalisé (affiche le texte par défaut)", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'En-tête Section Équipe',
                'verbose_name_plural': 'En-tête Section Équipe',
            },
        ),
    ]
