# Generated by Django 5.2.7 on 2025-10-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_teamheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamheader',
            name='description',
            field=models.TextField(blank=True, help_text='Description affichée sous le titre (optionnel)', max_length=300, null=True, verbose_name='Description'),
        ),
    ]
