# Generated by Django 5.2.7 on 2025-10-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_teamheader_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='Pinnacle Advisors - Cabinet de Conseil Expert', help_text='Titre principal affiché dans les résultats de recherche (60 caractères max recommandé)', max_length=200, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(default="Cabinet de conseil spécialisé en optimisation et transformation des chaînes d'approvisionnement. Expertise 360° pour faire de votre supply chain un avantage compétitif.", help_text='Description affichée dans les résultats de recherche (155 caractères max recommandé)', max_length=300, verbose_name='Description SEO')),
                ('meta_keywords', models.CharField(default='supply chain, logistique, conseil, optimisation, transformation digitale, WMS, TMS, S&OP', help_text='Mots-clés séparés par des virgules', max_length=500, verbose_name='Mots-clés SEO')),
                ('author_name', models.CharField(default='Pinnacle Advisors', help_text="Nom de l'auteur du site (métadonnée author)", max_length=100, verbose_name="Nom de l'auteur")),
                ('og_title', models.CharField(default='Pinnacle Advisors - Cabinet de Conseil Expert', help_text='Titre affiché lors du partage sur les réseaux sociaux', max_length=200, verbose_name='Titre OpenGraph')),
                ('og_description', models.TextField(default='Transformez votre supply chain en avantage compétitif', help_text='Description affichée lors du partage sur les réseaux sociaux', max_length=300, verbose_name='Description OpenGraph')),
                ('og_locale', models.CharField(default='fr_FR', help_text='Langue et région (ex: fr_FR, en_US)', max_length=10, verbose_name='Locale OpenGraph')),
                ('og_image', models.ImageField(blank=True, help_text='Image affichée lors du partage (1200x630px recommandé)', null=True, upload_to='seo/', verbose_name='Image OpenGraph')),
                ('is_active', models.BooleanField(default=True, help_text='Une seule configuration SEO peut être active à la fois', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Configuration SEO',
                'verbose_name_plural': 'Configuration SEO',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Pinnacle Advisors', help_text='Nom affiché dans la navbar et le footer', max_length=100, verbose_name="Nom de l'entreprise")),
                ('company_tagline', models.TextField(default="Cabinet de conseil expert en optimisation et transformation des chaînes d'approvisionnement.", help_text='Description courte affichée dans le footer', max_length=500, verbose_name='Slogan entreprise')),
                ('navbar_cta_text', models.CharField(default='Demander un devis', help_text="Texte du bouton d'appel à l'action dans la barre de navigation", max_length=50, verbose_name='Texte CTA Navbar')),
                ('mobile_menu_cta_text', models.CharField(default='Demander un devis', help_text='Texte du bouton CTA dans le menu mobile', max_length=50, verbose_name='Texte CTA Menu Mobile')),
                ('footer_nav_title', models.CharField(default='Navigation', help_text='Titre de la section navigation dans le footer', max_length=50, verbose_name='Titre Navigation Footer')),
                ('footer_services_title', models.CharField(default='Nos Services', help_text='Titre de la section services dans le footer', max_length=50, verbose_name='Titre Services Footer')),
                ('footer_follow_title', models.CharField(default='Suivez-nous', help_text='Titre de la section réseaux sociaux dans le footer', max_length=50, verbose_name='Titre Réseaux Sociaux Footer')),
                ('footer_hours_label', models.CharField(default="Horaires d'ouverture", help_text="Label affiché avant les horaires d'ouverture", max_length=50, verbose_name='Label Horaires Footer')),
                ('footer_copyright_text', models.CharField(default='© {year} Pinnacle Advisors. Tous droits réservés.', help_text='Texte de copyright ({year} sera remplacé automatiquement)', max_length=200, verbose_name='Texte Copyright')),
                ('footer_legal_text', models.CharField(default='Mentions légales', help_text='Texte du lien vers les mentions légales', max_length=50, verbose_name='Texte Lien Mentions Légales')),
                ('footer_privacy_text', models.CharField(default='Politique de confidentialité', help_text='Texte du lien vers la politique de confidentialité', max_length=50, verbose_name='Texte Lien Confidentialité')),
                ('footer_terms_text', models.CharField(default='CGV', help_text='Texte du lien vers les conditions générales de vente', max_length=50, verbose_name='Texte Lien CGV')),
                ('is_active', models.BooleanField(default=True, help_text='Une seule configuration peut être active à la fois', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Paramètres du Site',
                'verbose_name_plural': 'Paramètres du Site',
            },
        ),
    ]
