"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from celery.schedules import crontab
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY must be set in .env file - no default for security
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    # Django admin interface (must be before django.contrib.admin)
    'admin_interface',
    'colorfield',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    'import_export',
    'django_celery_results',
    'django_celery_beat',
    'drf_spectacular',  # OpenAPI/Swagger documentation

    # Local apps
    'apps.core',
    'apps.website',
    'apps.crm',
    'apps.analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL on Render (DATABASE_URL env var), SQLite locally
if os.environ.get('DATABASE_URL'):
    # Production: PostgreSQL via DATABASE_URL (Render, Railway, etc.)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# Allow localhost for development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Add production origins from environment variable (Vercel, etc.)
if os.environ.get('CORS_ALLOWED_ORIGINS'):
    # Format: "https://domain1.com,https://domain2.com"
    production_origins = [
        origin.strip()
        for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
        if origin.strip()
    ]
    CORS_ALLOWED_ORIGINS.extend(production_origins)

CORS_ALLOW_CREDENTIALS = True

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # OpenAPI schema
}

# DRF Spectacular Configuration (OpenAPI/Swagger)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Pinnacle Advisors API',
    'DESCRIPTION': (
        'API REST complète pour le site web et CRM Pinnacle Advisors.\n\n'
        '**Features:**\n'
        '- Website Content API (Hero, Services, About, Team, FAQ, Contact)\n'
        '- CRM API (Leads, Pipelines, Interactions, Notes) - Admin only\n'
        '- Analytics Tracking API (Sessions, PageViews, Events, Heatmaps)\n\n'
        '**Permissions:**\n'
        '- Website API: Public (AllowAny)\n'
        '- CRM API: Admin only (IsAdminUser)\n'
        '- Analytics Tracking: Public (AllowAny)\n'
        '- Analytics Admin: Admin only (IsAdminUser)'
    ),
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'CONTACT': {
        'name': 'Pinnacle Advisors',
        'email': 'contact@pinnacle-advisors.tech',
    },
    'LICENSE': {
        'name': 'Propriétaire',
    },
    # Schemas for API views
    'SCHEMA_PATH_PREFIX': r'/api/',
    'SCHEMA_PATH_PREFIX_TRIM': True,
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Development server'},
        {'url': 'https://api.pinnacle-advisors.tech', 'description': 'Production server'},
    ],
    'TAGS': [
        {'name': 'website', 'description': 'Website content management endpoints'},
        {'name': 'crm', 'description': 'CRM endpoints (admin-only)'},
        {'name': 'analytics', 'description': 'Analytics tracking and reporting'},
    ],
}

# Email Configuration
# https://docs.djangoproject.com/en/5.2/topics/email/

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'  # Pour dev: affiche emails dans console
)

# SMTP Configuration (pour production)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@pinnacle-advisors.tech')
SERVER_EMAIL = config('SERVER_EMAIL', default='admin@pinnacle-advisors.tech')

# Emails destinataires pour notifications CRM
CRM_NOTIFICATION_EMAILS = config(
    'CRM_NOTIFICATION_EMAILS',
    default='contact@pinnacle-advisors.tech',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': config('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'apps.website': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.crm': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Celery Configuration
# https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html

# Broker settings (Redis)
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'  # Stocker les résultats dans la DB Django
CELERY_CACHE_BACKEND = 'django-cache'

# Time settings
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Task settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max par task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Avertissement à 25 minutes

# Serialization
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Result backend settings
CELERY_RESULT_EXTENDED = True

# Beat scheduler (pour tâches périodiques)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Beat schedule - Tâches périodiques
CELERY_BEAT_SCHEDULE = {
    # Agrégation quotidienne des analytics (chaque jour à 00:05)
    'aggregate-daily-analytics': {
        'task': 'analytics.aggregate_daily_analytics',
        'schedule': crontab(hour=0, minute=5),
        'options': {
            'expires': 3600,  # Expire après 1h si pas exécutée
        }
    },
    # Nettoyage des vieilles données heatmap (chaque dimanche à 02:00)
    'cleanup-old-heatmap': {
        'task': 'analytics.cleanup_old_heatmap_data',
        'schedule': crontab(hour=2, minute=0, day_of_week=0),
        'kwargs': {'days': 180},  # Conserver 6 mois
        'options': {
            'expires': 7200,
        }
    },
}

# Email settings pour Celery (utilisera les mêmes que Django)
CELERY_EMAIL_BACKEND = EMAIL_BACKEND

# ============================================================================
# PRODUCTION SETTINGS (Render, Railway, etc.)
# ============================================================================

# Detect if running on Render or other production platforms
IS_RENDER = os.environ.get('RENDER', False)
IS_PRODUCTION = IS_RENDER or os.environ.get('PRODUCTION', False)

if IS_PRODUCTION:
    # Security settings for production
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Logging for production
    LOGGING['loggers']['django']['level'] = 'WARNING'
    LOGGING['loggers']['apps.website']['level'] = 'WARNING'
    LOGGING['loggers']['apps.crm']['level'] = 'INFO'  # Keep INFO for CRM to track leads
