# Generated by Django 5.2.7 on 2025-10-27 02:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du pipeline')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('company_size', models.CharField(choices=[('tpe', 'TPE (< 50 employés)'), ('pme', 'PME (50-200 employés)'), ('eti', 'ETI (200-5000 employés)'), ('ge', 'Grande entreprise (> 5000 employés)'), ('unknown', 'Inconnu')], default='unknown', max_length=20, verbose_name='Taille entreprise')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Poste')),
                ('need_type', models.CharField(max_length=100, verbose_name='Type de besoin')),
                ('message', models.TextField(verbose_name='Message initial')),
                ('budget_mentioned', models.BooleanField(default=False, verbose_name='Budget mentionné')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget estimé (€)')),
                ('qualification', models.CharField(choices=[('hot', 'Hot - Priorité haute'), ('warm', 'Warm - Priorité moyenne'), ('cold', 'Cold - Priorité basse'), ('unqualified', 'Non qualifié')], default='unqualified', max_length=20, verbose_name='Qualification')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('qualified', 'Qualifié'), ('proposal', 'Proposition envoyée'), ('negotiation', 'Négociation'), ('won', 'Gagné'), ('lost', 'Perdu'), ('on_hold', 'En attente')], default='new', max_length=20, verbose_name='Statut')),
                ('score', models.IntegerField(default=0, help_text='Score calculé automatiquement (0-100)', verbose_name='Score de qualification')),
                ('source', models.CharField(choices=[('website', 'Site web'), ('referral', 'Recommandation'), ('linkedin', 'LinkedIn'), ('email', 'Email'), ('phone', 'Téléphone'), ('event', 'Événement'), ('other', 'Autre')], default='website', max_length=20, verbose_name='Source')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('converted_to_client', models.BooleanField(default=False, verbose_name='Converti en client')),
                ('conversion_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de conversion')),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Revenu attendu (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernier contact')),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Prochain suivi')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Appel'), ('meeting', 'Réunion'), ('note', 'Note')], max_length=20, verbose_name='Type')),
                ('subject', models.CharField(max_length=300, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privé')),
                ('is_important', models.BooleanField(default=False, verbose_name='Important')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
